### ISSUE TITLE
SOCI 101 broken buttons

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#215]
**Describe the error and/or your suggestion**  
Units 2-7 -in the Assessment section - there is a button at the bottom of the page that is an error page.  Colin, I think you said we needed to move this folder then?  And check all references to images in the folder are redirected?
Please help!

**Comment by faitht1023** [comment]
@kmarjanovic are you referring to the PDF that's linked at the bottom of the assignments? Currently, the PDF does not exist in the folder. Would you know where I can get it from?

**Comment by kmarjanovic** [comment]
Hi Faith,
No, there's no pdf that needs to be linked.
It's a glitch I think Colin solved last week but not sure how to fix it.

Unit 2 assessment shows "Schedule button"; Unit 3 shows "Media" button. etc. with other buttons that shouldn't be there. (see course in Moodle)

@cmadland can you help or explain to us?
![image](https://user-images.githubusercontent.com/35148983/74189526-cfa1e180-4c0d-11ea-9078-2fa161588a2c.png)

**Comment by kmarjanovic** [comment]
This is still unresolved.  @cmadland could you help?

**Comment by cmadland** [comment]
Should be fixed.

**Comment by kmarjanovic** [comment]
@cmadland  it's still there for Units 2-7.

**Comment by cmadland** [comment]
@kmarjanovic @JessD9  do you have time to meet in the Design Zoom to chat...I know what is wrong here but I fear that the 'fix' will cause chaos

**Comment by kmarjanovic** [comment]
Yikes!  What happened to the units?

See [Unit 3](https://learn.twu.ca/course/view.php?id=10781&section=3) - overview missing, assessment at the top?


Original button issue not solved yet.

**Comment by kmarjanovic** [comment]
@rezakh66  @cmadland 

Original request from January still needs to be fixed.

**Comment by rezakh66** [comment]
@kmarjanovic Hi, I think I have removed the buttons successfully. let me know if any change is needed

**Comment by kmarjanovic** [comment]
Thank you @rezakh66 !
